info:
   app:
    name: search-engine

server:
  port: 8000

spring:
  application:
    name: ${info.app.name}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/the_bad_touch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    com:
      thebadtouch: DEBUG


---
spring:
  profiles: windows

application:
  files-to-index: "files/"
  encoding: "Cp1252"


---
spring:
  profiles: linux

application:
  files-to-index: "/home/user/workspaces/search-engine/files/"
  encoding: "Cp1252"