info:
   app:
    name: search-engine

server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ${info.app.name}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 1000
          batch_size_insert: 1000
          batch_size_delete: 1000
  datasource:
    url: jdbc:postgresql://localhost:5432/the_bad_touch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    com:
      thebadtouch: INFO

document-limit: 5
---
spring:
  profiles: local

application:
  files-to-index: "files/"
  new-files: "new_files/"
  encoding: "Cp1252"


---
spring:
  profiles: remote

application:
  files-to-index: "files/"
  encoding: "Cp1252"

logging:
  level:
    com:
      apc: DEBUG
  file:
    name: /opt/search-engine/logs/search-engine.log